package com.mcquilleninteractive.learnhvac.event
{
	/* Handles events generated by user clicking on MiniNav within simulation window (or using other nav
	   mechanism in this window*/
	  
	 
	import flash.events.Event
	
	public class SimNavEvent extends Event
	{
		
		public static const NAVIGATION:String = "simNavEvent"
		
		public var node:String
		
		public function SimNavEvent(type:String, bubbles:Boolean=false, cancelable:Boolean=false)
		{			
			super(type, bubbles, cancelable);
		}	
						

		public override function clone():Event
		{
			return new SimNavEvent(this.type, this.bubbles, this.cancelable)
		}
		
	}
}