package com.mcquilleninteractive.learnhvac.view.event
{
	/* Handles events generated by user clicking on MiniNav within simulation window (or using other nav
	   mechanism in this window*/
	  
	 
	import flash.events.Event
	
	public class SimNavEvent extends Event
	{
		
		public static const EVENT_NAVIGATION:String = "simNav"
		
		private var _node:String
		
		public function get node():String
		{
			return _node
		}
		
		public function SimNavEvent(type:String, node:String)
		{
			super(type,true)
			_node = node
		}

		public override function clone():Event
		{
			return new SimNavEvent(type,_node)
		}
		
	}
}